local d = (import 'github.com/jsonnet-libs/docsonnet/doc-util/main.libsonnet');
{
  '#':: d.pkg(name='azuread', url='', help='The `azuread` package contains functions and utilities for setting up the provider, resources, and data\nsources of the [azuread Terraform provider](TODO) using Jsonnet.\n\nThis package is autogenerated from the [tf-libsonnet/libgenerator](https://github.com/tf-libsonnet/libgenerator)\nproject.\n'),
  provider: (import 'provider_azuread.libsonnet'),
  data: (import 'data/main.libsonnet'),
} + (import 'resources/main.libsonnet')
